test:
  restart: "always"
  image: mordred
  volumes:
    - /home/luis/conf/:/home/bitergia/conf
  links:
    - mariadb

mariadb:
  restart: "always"
  image: mariadb:10.0
  expose:
    - "3306"
  environment:
    - MYSQL_ROOT_PASSWORD=
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes

