elasticsearch:
  # image: elasticsearch:5.6.0
  image: docker.elastic.co/elasticsearch/elasticsearch:5.6.0
  command: elasticsearch -E network.bind_host=0.0.0.0 -E xpack.security.enabled=false
  # command: /elasticsearch/bin/elasticsearch -E network.bind_host=0.0.0.0
  ports:
    - "9200:9200"
  environment:
    - ES_JAVA_OPTS=-Xms2g -Xmx2g
  # volumes:
  #  - ./elasticsearch.yml:/elasticsearch/config/elasticsearch.yml

kibiter:
  image: docker.elastic.co/kibana/kibana:5.6.0
  links:
    - elasticsearch
  ports:
    - "5601:5601"
  environment:
    # - ELASTICSEARCH_URL=http://172.17.0.1:9200 
    # - ELASTICSEARCH_USER=bitergia
    # - ELASTICSEARCH_PASSWORD=bitergia
    # - PROJECT_NAME=Test20
    # - NODE_OPTIONS=--max-old-space-size=1000
    - XPACK_GRAPH_ENABLED=false
    - XPACK_MONITORING_ENABLED=false
    - XPACK_REPORTING_ENABLED=false
    - XPACK_SECURITY_ENABLED=false
    - XPACK_ML_ENABLED=false

# gelk-lite:
#     image: bitergia/gelk-lite
#     links:
#         - elasticsearch
